[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[deploy.environmentVariables]]
name = "MQTT_PORT"
value = "1883"

[[deploy.environmentVariables]]
name = "HTTP_PORT"
value = "8000"

[[deploy.environmentVariables]]
name = "NODE_RED_USERNAME"
value = "admin"

[[deploy.environmentVariables]]
name = "NODE_RED_PASSWORD_HASH"
value = "$2a$08$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN."

[[deploy.environmentVariables]]
name = "NODE_RED_CREDENTIAL_SECRET"
value = "railway-node-red-secret-key"
